name: Docker Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: hriver1224/springboot-app
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: SSH to Deploy Server via Jump Host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.JUMP_HOST }}
          username: ${{ secrets.JUMP_USER }}
          password: ${{ secrets.JUMP_PASSWORD }}
          port: ${{ secrets.JUMP_PORT }}
          script: |
            sshpass -p ${{ secrets.PRIVATE_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.PRIVATE_SERVER_USER }}@${{ secrets.PRIVATE_SERVER_HOST }} << 'EOF'
              docker pull ${{ env.DOCKER_IMAGE_NAME }}:latest
              docker stop springboot_app || true
              docker rm springboot_app || true
              docker run -d -p 8080:8080 --name springboot_app ${{ env.DOCKER_IMAGE_NAME }}:latest
            EOF
